export const ROOMS = [
  {
    id: 'about',
    number: '01',
    label: 'ABOUT',
    symbol: '◎',
    color: '#e96a4d',
    colorValue: 0xe96a4d,
    side: -1,
    z: -11,
    doorScale: 1.03,
    landmarkScale: 1.1,
    stage: 'workbench',
    camera: {
      approach: [-0.5, 0.05, -6.8],
      approachLook: [-7.7, 0, -11],
      position: [-10.2, 0.15, -7.1],
      lookAt: [-12.35, -0.15, -11.3],
      mobile: {
        position: [-9.7, 1.1, -7.4],
        lookAt: [-12.3, -1.35, -11.1],
      },
    },
    content: {
      title: 'Building paths from language to motion.',
      description: 'I\'m Tao, a Mechatronics Engineering student at Xi\'an Jiaotong-Liverpool University. I work at the boundary of vision-language navigation, robotics software, and STM32-based embedded systems—interested in how a robot can turn what it sees and is told into safe, useful action.',
      fields: [
        ['Current work', 'I am developing a vision-language navigation pipeline that links camera observations and remote model inference to a ROS 2 vehicle stack, then sends safety-bounded motion commands to an STM32-connected chassis.'],
        ['Working style', 'I pair closed-loop navigation experiments in Habitat with hands-on embedded work in C: I2C displays, timer systems, and STM32G4 application projects.'],
      ],
    },
  },
  {
    id: 'gallery',
    number: '02',
    label: 'GALLERY',
    symbol: '▧',
    color: '#7590ef',
    colorValue: 0x7590ef,
    side: 1,
    z: -18,
    doorScale: 1.1,
    landmarkScale: 1.26,
    stage: 'gallery-wall',
    camera: {
      approach: [0.5, 0.05, -13.8],
      approachLook: [7.7, 0, -18],
      position: [10.2, 0.18, -14.1],
      lookAt: [12.35, -0.15, -18.1],
      mobile: {
        position: [9.8, 0.85, -14.4],
        lookAt: [14.5, -1.2, -18],
      },
    },
    content: {
      title: 'Systems, with evidence.',
      description: 'A small selection of public work across navigation, simulation, and embedded control—each chosen for the link it makes between an idea and a working system.',
      fields: [
        ['Vision-language navigation', 'A camera-to-inference-to-control pipeline: observations go to a remote model, safety-bounded motion returns through ROS 2, and an STM32-connected chassis carries it out.'],
        ['Habitat experiments', 'Closed-loop navigation work in simulation, used to test the distance between a promising instruction-following idea and a dependable policy.'],
        ['STM32 systems', 'C projects that make the physical layer tangible: I2C display work, timer systems, and STM32G4 application experiments.'],
      ],
    },
  },
  {
    id: 'studio',
    number: '03',
    label: 'STUDIO',
    symbol: '∷',
    color: '#4eaf81',
    colorValue: 0x4eaf81,
    side: -1,
    z: -26,
    doorScale: 1.15,
    landmarkScale: 1.42,
    stage: 'project-table',
    camera: {
      approach: [-0.5, 0.05, -21.8],
      approachLook: [-7.7, 0, -26],
      position: [-10.2, 0.15, -22.1],
      lookAt: [-12.35, -0.1, -26.15],
      mobile: {
        position: [-9.7, 1.1, -22.4],
        lookAt: [-12.3, -1.3, -26],
      },
    },
    content: {
      title: 'A record of making.',
      description: 'The work is not a straight line from model to robot. This room holds the useful middle: tests, constraints, implementation details, and the revisions that make a system more dependable.',
      fields: [
        ['Method', 'I move between simulation and hardware: observe a closed loop in Habitat, inspect the ROS 2 control path, then test the embedded boundary that reaches the chassis.'],
        ['Evidence', 'A project earns a place here when it records the question, a reproducible constraint, and the outcome that changed the next decision.'],
      ],
    },
  },
  {
    id: 'contact',
    number: '04',
    label: 'CONTACT',
    symbol: '↗',
    color: '#d8b449',
    colorValue: 0xd8b449,
    side: 1,
    z: -34,
    doorScale: 1.19,
    landmarkScale: 1.58,
    stage: 'message-desk',
    camera: {
      approach: [0.5, 0.05, -29.8],
      approachLook: [7.7, 0, -34],
      position: [10.2, 0.15, -30.1],
      lookAt: [12.35, -0.1, -34.1],
      mobile: {
        position: [9.2, 1.15, -30],
        lookAt: [12.9, -1.15, -33.8],
      },
    },
    content: {
      title: 'Leave a door open.',
      description: 'When the portfolio is ready, this final desk can hold a preferred contact route and a small invitation to continue the conversation.',
      fields: [
        ['Preferred route', 'Add one contact channel you actively maintain.'],
        ['A good starting point', 'Add a short cue for the kind of conversation you welcome.'],
      ],
    },
  },
];

export const ROOM_BY_ID = new Map(ROOMS.map((room) => [room.id, room]));
